name: Build Operator

on:
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore

env:
  APP_NAME: go-hello
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 0

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Go fmt
        run: go fmt

      - name: Go vet
        run: go vet

      - name: Go test
        run: go test

      - name: Build
        run: go build -v -a -o ${{ env.APP_NAME }} main.go

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP_NAME }}
          path: ./${{ env.APP_NAME }}
